name: "Other"

on:
  push:
  workflow_dispatch:
  pull_request:
  pull_request_target:

jobs:
  other:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
