name: "Other"

on:
  pull_request:

jobs:
  other:
    runs-on: ubuntu-latest

    steps:
      # This should trigger a missing actions permissions alert.
      - name: Checkout repository
        uses: actions/checkout@main
