name: "Other"

on:
  push:
  workflow_dispatch:
  pull_request:
  workflow_run:

jobs:
  other:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
